# Generated by Django 5.1.7 on 2026-06-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Free-text referral source (e.g., "walk-in", "school teacher", "old patient")', max_length=255),
        ),
    ]
