# Generated by Django 5.1.7 on 2026-06-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_referral_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='import_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount captured from imported clinic files', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='import_notes',
            field=models.TextField(blank=True, help_text='Additional details captured from imported clinic files'),
        ),
        migrations.AddField(
            model_name='patient',
            name='import_visit_date',
            field=models.DateField(blank=True, help_text='Visit/date captured from imported clinic files', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
