# Generated by Django 5.1.7 on 2026-04-15 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_by_name', models.CharField(blank=True, max_length=100)),
                ('referred_by_phone', models.CharField(blank=True, max_length=15)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=15)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('patient_address', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True, help_text='Why are you referring this patient?')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('registered', 'Registered as Patient'), ('closed', 'Closed')], default='new', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'db_table': 'referrals',
                'ordering': ['-created_at'],
            },
        ),
    ]
