# Generated by Django 5.1.7 on 2026-05-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Link to generated PDF on Dropbox', null=True),
        ),
    ]
