# Generated by Django 5.1.7 on 2026-06-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_udhari',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='udhari_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='udhari_last_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='udhari_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('insurance', 'Insurance'), ('udhari', 'Udhari (Credit)'), ('other', 'Other')], default='cash', max_length=15),
        ),
    ]
