# Generated by Django 5.1.7 on 2026-05-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategory_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_patients',
            field=models.BooleanField(default=False, help_text='Available for doctor prescriptions'),
        ),
        migrations.AddField(
            model_name='product',
            name='for_public',
            field=models.BooleanField(default=True, help_text='Visible on public health store'),
        ),
    ]
