# Generated by Django 5.1.7 on 2026-05-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_for_patients_product_for_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_quantity',
            field=models.CharField(blank=True, help_text='e.g. 500ml, 100 Tablets', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
