# Generated by Django 5.1.7 on 2026-05-08 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('products', '0005_product_display_quantity_product_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Threshold for low stock alert'),
        ),
        migrations.CreateModel(
            name='ProductStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Stock Adjustment')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, help_text='E.g., Order #45, Manual top-up', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_ledger', to='branches.branch')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stock_actions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Stock Ledger',
                'verbose_name_plural': 'Product Stock Ledgers',
                'db_table': 'product_stock_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
