# Generated by Django 5.1.7 on 2026-05-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_attendance_is_flagged_attendance_recorded_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
    ]
