# Generated by Django 5.1.7 on 2026-05-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_salary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PayrollSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10)),
                ('present_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('paid_leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('absent_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('holiday_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_slips', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Payroll Slip',
                'verbose_name_plural': 'Payroll Slips',
                'db_table': 'payroll_slips',
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
