# Generated by Django 5.1.7 on 2026-06-11 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_hospital_is_active'),
        ('hr', '0005_leaveapplication_is_half_day_payrollslip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollslip',
            name='lop_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='BranchOvertimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('flat', 'Flat Hourly Rate'), ('1.5x', '1.5x Base Hourly Rate'), ('2x', '2.0x Base Hourly Rate')], default='1.5x', max_length=10)),
                ('flat_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Only used if rate_type is flat', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_config', to='branches.branch')),
            ],
            options={
                'db_table': 'branch_overtime_configs',
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='hr.employee')),
            ],
            options={
                'db_table': 'overtime_records',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
