# Generated by Django 5.1.7 on 2026-05-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('note', 'Note')], default='call', max_length=15),
        ),
    ]
