# Generated by Django 5.1.7 on 2026-06-11 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0006_hospital_is_active'),
        ('medicines', '0005_medicine_low_stock_threshold_medicinestockledger'),
        ('patients', '0006_patient_import_amount_patient_import_notes_and_more'),
        ('products', '0007_product_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('therapy_type', models.CharField(choices=[('sujok', 'Sujok'), ('acupuncture', 'Acupuncture'), ('physiotherapy', 'Physiotherapy'), ('ayurvedic', 'Ayurvedic'), ('yoga', 'Yoga'), ('panchakarma', 'Panchakarma'), ('other', 'Other')], max_length=50)),
                ('materials_needed', models.TextField(blank=True, help_text='Herbs, oils, equipment, etc.')),
                ('total_duration_days', models.PositiveIntegerField(help_text='Total therapy program length in days')),
                ('sessions_per_week', models.PositiveIntegerField(default=2)),
                ('session_duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, help_text='Which branches offer this therapy', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicines', models.ManyToManyField(blank=True, to='medicines.medicine')),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
            ],
            options={
                'verbose_name': 'Therapy',
                'verbose_name_plural': 'Therapies',
                'db_table': 'therapies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientTherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapies', to='patients.patient')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='therapies.therapy')),
            ],
            options={
                'db_table': 'patient_therapies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapyTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Day 1, Day 7, Day 14...')),
                ('session_label', models.CharField(help_text='e.g. "Initial Assessment"', max_length=100)),
                ('practices', models.TextField(help_text='What to do on this day')),
                ('notes', models.TextField(blank=True)),
                ('medicines_on_day', models.ManyToManyField(blank=True, to='medicines.medicine')),
                ('products_on_day', models.ManyToManyField(blank=True, to='products.product')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='therapies.therapy')),
            ],
            options={
                'db_table': 'therapy_timelines',
                'ordering': ['day_number'],
            },
        ),
    ]
