# Generated by Django 5.1.7 on 2026-04-15 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('medicines', '0002_initial'),
        ('patients', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignattendance',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_attendance', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignmanagerassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_assignments_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignmanagerassignment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignmanagerassignment',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'employee']}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignpatient',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_patients', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignpatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_registrations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='campaignpatient',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_patient_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignsale',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignsale',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_sales', to='medicines.medicine'),
        ),
        migrations.AddField(
            model_name='campaignsale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_sales', to='products.product'),
        ),
        migrations.AddField(
            model_name='campaignsale',
            name='sold_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='campaignattendance',
            unique_together={('campaign', 'user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignmanagerassignment',
            unique_together={('campaign', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignpatient',
            unique_together={('campaign', 'patient')},
        ),
    ]
