# Generated by Django 5.1.7 on 2026-05-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='attendance_radius_meters',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
