# Generated by Django 5.1.7 on 2026-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_attendance_radius_meters_branch_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='shift_end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='branch',
            name='shift_start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
