# Generated by Django 5.1.7 on 2026-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_shift_end_time_branch_shift_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='max_patients_per_slot',
            field=models.IntegerField(default=5),
        ),
    ]
