# Generated by Django 5.1.7 on 2026-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_max_patients_per_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
