# Generated by Django 5.1.7 on 2026-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('accountant', 'Accountant'), ('marketing', 'Marketing'), ('employee', 'Employee'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
