# Generated by Django 5.1.7 on 2026-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('employee', 'Employee'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
