# Generated by Django 5.1.7 on 2026-05-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
        ('users', '0003_clean_roles_to_five'),
    ]

    operations = [
    ]
