# Generated by Django 5.1.7 on 2026-05-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_initial'),
        ('products', '0004_product_for_patients_product_for_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='medicines.medicine'),
        ),
    ]
