# Generated by Django 5.1.7 on 2026-05-08 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('medicines', '0004_prescriptionitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Threshold for low stock alert'),
        ),
        migrations.CreateModel(
            name='MedicineStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Stock Adjustment')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, help_text='E.g., Prescription #12, Manual top-up', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_stock_ledger', to='branches.branch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='medicines.medicine')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_stock_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicine Stock Ledger',
                'verbose_name_plural': 'Medicine Stock Ledgers',
                'db_table': 'medicine_stock_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
